if(EXISTS "/Users/michaelhalloran/cube_edit/build_debug/core/surface_gen/tests/test_unit_core_surface_gen_topology_preserver[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_debug/core/surface_gen/tests/test_unit_core_surface_gen_topology_preserver[1]_tests.cmake")
else()
  add_test(test_unit_core_surface_gen_topology_preserver_NOT_BUILT test_unit_core_surface_gen_topology_preserver_NOT_BUILT)
endif()
