add_test([=[SurfaceGenPerformanceTest.EmptyGridPerformance]=]  /Users/michaelhalloran/cube_edit/build_debug/bin/test_unit_core_surface_gen_performance [==[--gtest_filter=SurfaceGenPerformanceTest.DISABLED_EmptyGridPerformance]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SurfaceGenPerformanceTest.EmptyGridPerformance]=]  PROPERTIES DISABLED TRUE)
set_tests_properties([=[SurfaceGenPerformanceTest.EmptyGridPerformance]=]  PROPERTIES WORKING_DIRECTORY /Users/michaelhalloran/cube_edit/build_debug/core/surface_gen/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SurfaceGenPerformanceTest.NEONPerformance]=]  /Users/michaelhalloran/cube_edit/build_debug/bin/test_unit_core_surface_gen_performance [==[--gtest_filter=SurfaceGenPerformanceTest.DISABLED_NEONPerformance]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SurfaceGenPerformanceTest.NEONPerformance]=]  PROPERTIES DISABLED TRUE)
set_tests_properties([=[SurfaceGenPerformanceTest.NEONPerformance]=]  PROPERTIES WORKING_DIRECTORY /Users/michaelhalloran/cube_edit/build_debug/core/surface_gen/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SurfaceGenPerformanceTest.SparseGridPerformance]=]  /Users/michaelhalloran/cube_edit/build_debug/bin/test_unit_core_surface_gen_performance [==[--gtest_filter=SurfaceGenPerformanceTest.DISABLED_SparseGridPerformance]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SurfaceGenPerformanceTest.SparseGridPerformance]=]  PROPERTIES DISABLED TRUE)
set_tests_properties([=[SurfaceGenPerformanceTest.SparseGridPerformance]=]  PROPERTIES WORKING_DIRECTORY /Users/michaelhalloran/cube_edit/build_debug/core/surface_gen/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SurfaceGenPerformanceTest.DenseGridPerformance]=]  /Users/michaelhalloran/cube_edit/build_debug/bin/test_unit_core_surface_gen_performance [==[--gtest_filter=SurfaceGenPerformanceTest.DISABLED_DenseGridPerformance]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SurfaceGenPerformanceTest.DenseGridPerformance]=]  PROPERTIES DISABLED TRUE)
set_tests_properties([=[SurfaceGenPerformanceTest.DenseGridPerformance]=]  PROPERTIES WORKING_DIRECTORY /Users/michaelhalloran/cube_edit/build_debug/core/surface_gen/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_unit_core_surface_gen_performance_TESTS SurfaceGenPerformanceTest.EmptyGridPerformance SurfaceGenPerformanceTest.NEONPerformance SurfaceGenPerformanceTest.SparseGridPerformance SurfaceGenPerformanceTest.DenseGridPerformance)
