# CMake generated Testfile for 
# Source directory: /Users/michaelhalloran/cube_edit/apps/cli/tests
# Build directory: /Users/michaelhalloran/cube_edit/build_test/apps/cli/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_unit_cli_arbitrary_positions[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_unit_cli_camera_command_validation[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_unit_cli_camera_commands[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_unit_cli_command_error_handling[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_unit_cli_coordinate_system_constraints[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_unit_cli_mouse_interaction[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_unit_cli_place_command[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_unit_cli_ray_generation_accuracy[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_unit_cli_remove_command[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_unit_cli_resolution_command[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_unit_cli_same_size_voxel_alignment[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_unit_cli_select_commands[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_unit_cli_smoothing_commands[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_unit_cli_voxel_mesh_generator[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_unit_cli_workspace_command_validation[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_cli_application[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_cli_command_registry[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_cli_command_sequences[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_cli_command_system[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_cli_command_validation[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_cli_commands[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_cli_error_handling[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_cli_face_click_comprehensive[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_cli_headless[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_cli_mouse_face_placement[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_cli_ray_visualization[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_cli_rendering[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_cli_rendering_basic[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_cli_smoothing_export[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_cli_undo_redo_chains[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_interaction_click_voxel_placement[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_interaction_face_clicking[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_interaction_mouse_ray_movement[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_interaction_voxel_face_clicking[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_interaction_voxel_face_clicking_simple[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_interaction_zoom_behavior[1]_include.cmake")
