if(EXISTS "/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_unit_cli_coordinate_system_constraints[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_unit_cli_coordinate_system_constraints[1]_tests.cmake")
else()
  add_test(test_unit_cli_coordinate_system_constraints_NOT_BUILT test_unit_cli_coordinate_system_constraints_NOT_BUILT)
endif()
