if(EXISTS "/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_cli_mouse_face_placement[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_test/apps/cli/tests/test_integration_cli_mouse_face_placement[1]_tests.cmake")
else()
  add_test(test_integration_cli_mouse_face_placement_NOT_BUILT test_integration_cli_mouse_face_placement_NOT_BUILT)
endif()
