if(EXISTS "/Users/michaelhalloran/cube_edit/build_test/core/voxel_data/tests/test_unit_core_voxel_data_types[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_test/core/voxel_data/tests/test_unit_core_voxel_data_types[1]_tests.cmake")
else()
  add_test(test_unit_core_voxel_data_types_NOT_BUILT test_unit_core_voxel_data_types_NOT_BUILT)
endif()
