if(EXISTS "/Users/michaelhalloran/cube_edit/build_test/foundation/math/tests/test_unit_foundation_math_coordinate_types[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_test/foundation/math/tests/test_unit_foundation_math_coordinate_types[1]_tests.cmake")
else()
  add_test(test_unit_foundation_math_coordinate_types_NOT_BUILT test_unit_foundation_math_coordinate_types_NOT_BUILT)
endif()
