if(EXISTS "/Users/michaelhalloran/cube_edit/build_debug/core/undo_redo/tests/test_unit_core_undo_redo_history_manager[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_debug/core/undo_redo/tests/test_unit_core_undo_redo_history_manager[1]_tests.cmake")
else()
  add_test(test_unit_core_undo_redo_history_manager_NOT_BUILT test_unit_core_undo_redo_history_manager_NOT_BUILT)
endif()
