if(EXISTS "/Users/michaelhalloran/cube_edit/build_debug/core/camera/tests/test_unit_core_camera_camera[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_debug/core/camera/tests/test_unit_core_camera_camera[1]_tests.cmake")
else()
  add_test(test_unit_core_camera_camera_NOT_BUILT test_unit_core_camera_camera_NOT_BUILT)
endif()
