if(EXISTS "/Users/michaelhalloran/cube_edit/build_ninja/core/voxel_data/tests/VoxelEditor_VoxelData_Tests[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_ninja/core/voxel_data/tests/VoxelEditor_VoxelData_Tests[1]_tests.cmake")
else()
  add_test(VoxelEditor_VoxelData_Tests_NOT_BUILT VoxelEditor_VoxelData_Tests_NOT_BUILT)
endif()
