if(EXISTS "/Users/michaelhalloran/cube_edit/build_debug/core/groups/tests/test_unit_core_groups_manager[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_debug/core/groups/tests/test_unit_core_groups_manager[1]_tests.cmake")
else()
  add_test(test_unit_core_groups_manager_NOT_BUILT test_unit_core_groups_manager_NOT_BUILT)
endif()
