#pragma once

// This file is auto-generated by CMake during build
// DO NOT EDIT MANUALLY

namespace VoxelEditor {
namespace CLI {

// Build timestamp (Unix timestamp)
constexpr long BUILD_TIMESTAMP = 1750992351;

// Build date and time strings
constexpr const char* BUILD_DATE = "2025-06-26";
constexpr const char* BUILD_TIME = "22:45:51";

// Version information
constexpr const char* VERSION_STRING = "0.1.0";

// Git information (if available)
constexpr const char* GIT_COMMIT_HASH = "5183e74";
constexpr const char* GIT_BRANCH = "master";

// Build configuration
constexpr const char* BUILD_TYPE = "Debug";
constexpr const char* COMPILER_ID = "AppleClang";
constexpr const char* COMPILER_VERSION = "15.0.0.15000309";

} // namespace CLI
} // namespace VoxelEditor
