if(EXISTS "/Users/michaelhalloran/cube_edit/build_test/core/surface_gen/tests/test_integration_surface_gen_mock[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_test/core/surface_gen/tests/test_integration_surface_gen_mock[1]_tests.cmake")
else()
  add_test(test_integration_surface_gen_mock_NOT_BUILT test_integration_surface_gen_mock_NOT_BUILT)
endif()
