if(EXISTS "/Users/michaelhalloran/cube_edit/build_test/core/surface_gen/tests/test_unit_core_surface_gen_generator_optimized[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_test/core/surface_gen/tests/test_unit_core_surface_gen_generator_optimized[1]_tests.cmake")
else()
  add_test(test_unit_core_surface_gen_generator_optimized_NOT_BUILT test_unit_core_surface_gen_generator_optimized_NOT_BUILT)
endif()
