if(EXISTS "/Users/michaelhalloran/cube_edit/build_test/core/camera/tests/test_unit_core_camera_zoom_functionality[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_test/core/camera/tests/test_unit_core_camera_zoom_functionality[1]_tests.cmake")
else()
  add_test(test_unit_core_camera_zoom_functionality_NOT_BUILT test_unit_core_camera_zoom_functionality_NOT_BUILT)
endif()
