if(EXISTS "/Users/michaelhalloran/cube_edit/build_debug/foundation/config/tests/test_unit_foundation_config[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_debug/foundation/config/tests/test_unit_foundation_config[1]_tests.cmake")
else()
  add_test(test_unit_foundation_config_NOT_BUILT test_unit_foundation_config_NOT_BUILT)
endif()
