# CMake generated Testfile for 
# Source directory: /Users/michaelhalloran/cube_edit/apps/cli/tests
# Build directory: /Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_integration_cli_application[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_integration_cli_command_sequences[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_integration_cli_command_validation[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_integration_cli_commands[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_integration_cli_error_handling[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_integration_cli_headless[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_integration_cli_ray_visualization[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_integration_cli_rendering[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_integration_cli_rendering_basic[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_integration_cli_smoothing_export[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_integration_cli_undo_redo_chains[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_integration_interaction_click_voxel_placement[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_integration_interaction_face_clicking[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_integration_interaction_mouse_ray_movement[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_integration_interaction_voxel_face_clicking[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_integration_interaction_voxel_face_clicking_simple[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_integration_interaction_zoom_behavior[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_unit_cli_voxel_mesh_generator[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_unit_cli_coordinate_system_constraints[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_unit_cli_arbitrary_positions[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_unit_cli_select_commands[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_unit_cli_mouse_interaction[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_unit_cli_ray_generation_accuracy[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_stress_rapid_click_placement[1]_include.cmake")
include("/Users/michaelhalloran/cube_edit/build_debug/apps/cli/tests/test_unit_cli_smoothing_commands[1]_include.cmake")
add_test(cli_unit_tests "/Users/michaelhalloran/cube_edit/build_debug/bin/test_unit_cli_voxel_mesh_generator")
set_tests_properties(cli_unit_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/michaelhalloran/cube_edit/apps/cli/tests/CMakeLists.txt;101;add_test;/Users/michaelhalloran/cube_edit/apps/cli/tests/CMakeLists.txt;0;")
add_test(cli_coordinate_system_constraints_tests "/Users/michaelhalloran/cube_edit/build_debug/bin/test_unit_cli_coordinate_system_constraints")
set_tests_properties(cli_coordinate_system_constraints_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/michaelhalloran/cube_edit/apps/cli/tests/CMakeLists.txt;125;add_test;/Users/michaelhalloran/cube_edit/apps/cli/tests/CMakeLists.txt;0;")
add_test(cli_arbitrary_positions_tests "/Users/michaelhalloran/cube_edit/build_debug/bin/test_unit_cli_arbitrary_positions")
set_tests_properties(cli_arbitrary_positions_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/michaelhalloran/cube_edit/apps/cli/tests/CMakeLists.txt;148;add_test;/Users/michaelhalloran/cube_edit/apps/cli/tests/CMakeLists.txt;0;")
add_test(cli_select_commands_tests "/Users/michaelhalloran/cube_edit/build_debug/bin/test_unit_cli_select_commands")
set_tests_properties(cli_select_commands_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/michaelhalloran/cube_edit/apps/cli/tests/CMakeLists.txt;175;add_test;/Users/michaelhalloran/cube_edit/apps/cli/tests/CMakeLists.txt;0;")
add_test(cli_mouse_interaction_tests "/Users/michaelhalloran/cube_edit/build_debug/bin/test_unit_cli_mouse_interaction")
set_tests_properties(cli_mouse_interaction_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/michaelhalloran/cube_edit/apps/cli/tests/CMakeLists.txt;204;add_test;/Users/michaelhalloran/cube_edit/apps/cli/tests/CMakeLists.txt;0;")
add_test(cli_ray_generation_accuracy_tests "/Users/michaelhalloran/cube_edit/build_debug/bin/test_unit_cli_ray_generation_accuracy")
set_tests_properties(cli_ray_generation_accuracy_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/michaelhalloran/cube_edit/apps/cli/tests/CMakeLists.txt;228;add_test;/Users/michaelhalloran/cube_edit/apps/cli/tests/CMakeLists.txt;0;")
add_test(cli_stress_rapid_click_placement_tests "/Users/michaelhalloran/cube_edit/build_debug/bin/test_stress_rapid_click_placement")
set_tests_properties(cli_stress_rapid_click_placement_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/michaelhalloran/cube_edit/apps/cli/tests/CMakeLists.txt;260;add_test;/Users/michaelhalloran/cube_edit/apps/cli/tests/CMakeLists.txt;0;")
add_test(cli_smoothing_commands_tests "/Users/michaelhalloran/cube_edit/build_debug/bin/test_unit_cli_smoothing_commands")
set_tests_properties(cli_smoothing_commands_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/michaelhalloran/cube_edit/apps/cli/tests/CMakeLists.txt;284;add_test;/Users/michaelhalloran/cube_edit/apps/cli/tests/CMakeLists.txt;0;")
