if(EXISTS "/Users/michaelhalloran/cube_edit/build_test/core/visual_feedback/tests/test_unit_face_direction_accuracy[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_test/core/visual_feedback/tests/test_unit_face_direction_accuracy[1]_tests.cmake")
else()
  add_test(test_unit_face_direction_accuracy_NOT_BUILT test_unit_face_direction_accuracy_NOT_BUILT)
endif()
