if(EXISTS "/Users/michaelhalloran/cube_edit/build_debug/core/visual_feedback/tests/test_unit_core_visual_feedback_highlight_manager[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_debug/core/visual_feedback/tests/test_unit_core_visual_feedback_highlight_manager[1]_tests.cmake")
else()
  add_test(test_unit_core_visual_feedback_highlight_manager_NOT_BUILT test_unit_core_visual_feedback_highlight_manager_NOT_BUILT)
endif()
