if(EXISTS "/Users/michaelhalloran/cube_edit/build_test/tests/integration/rendering/test_integration_visual_reference_image_comparison[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_test/tests/integration/rendering/test_integration_visual_reference_image_comparison[1]_tests.cmake")
else()
  add_test(test_integration_visual_reference_image_comparison_NOT_BUILT test_integration_visual_reference_image_comparison_NOT_BUILT)
endif()
