if(EXISTS "/Users/michaelhalloran/cube_edit/build_test/foundation/logging/tests/test_unit_foundation_logging_logger[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_test/foundation/logging/tests/test_unit_foundation_logging_logger[1]_tests.cmake")
else()
  add_test(test_unit_foundation_logging_logger_NOT_BUILT test_unit_foundation_logging_logger_NOT_BUILT)
endif()
