if(EXISTS "/Users/michaelhalloran/cube_edit/build_debug/core/input/tests/test_unit_core_input_mapping[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_debug/core/input/tests/test_unit_core_input_mapping[1]_tests.cmake")
else()
  add_test(test_unit_core_input_mapping_NOT_BUILT test_unit_core_input_mapping_NOT_BUILT)
endif()
