if(EXISTS "/Users/michaelhalloran/cube_edit/build_debug/core/input/tests/test_unit_placement_snapping[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_debug/core/input/tests/test_unit_placement_snapping[1]_tests.cmake")
else()
  add_test(test_unit_placement_snapping_NOT_BUILT test_unit_placement_snapping_NOT_BUILT)
endif()
