if(EXISTS "/Users/michaelhalloran/cube_edit/build_debug/core/input/tests/VoxelEditor_Input_Tests[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_debug/core/input/tests/VoxelEditor_Input_Tests[1]_tests.cmake")
else()
  add_test(VoxelEditor_Input_Tests_NOT_BUILT VoxelEditor_Input_Tests_NOT_BUILT)
endif()
