if(EXISTS "/Users/michaelhalloran/cube_edit/build_debug/foundation/math/tests/test_unit_foundation_math[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_debug/foundation/math/tests/test_unit_foundation_math[1]_tests.cmake")
else()
  add_test(test_unit_foundation_math_NOT_BUILT test_unit_foundation_math_NOT_BUILT)
endif()
