if(EXISTS "/Users/michaelhalloran/cube_edit/build_test/core/input/tests/test_unit_core_input_modifier_key_tracking[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_test/core/input/tests/test_unit_core_input_modifier_key_tracking[1]_tests.cmake")
else()
  add_test(test_unit_core_input_modifier_key_tracking_NOT_BUILT test_unit_core_input_modifier_key_tracking_NOT_BUILT)
endif()
