if(EXISTS "/Users/michaelhalloran/cube_edit/build_test/core/groups/tests/test_unit_core_groups_hierarchy[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_test/core/groups/tests/test_unit_core_groups_hierarchy[1]_tests.cmake")
else()
  add_test(test_unit_core_groups_hierarchy_NOT_BUILT test_unit_core_groups_hierarchy_NOT_BUILT)
endif()
