if(EXISTS "/Users/michaelhalloran/cube_edit/build_ninja/core/selection/tests/VoxelEditor_Selection_Tests[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_ninja/core/selection/tests/VoxelEditor_Selection_Tests[1]_tests.cmake")
else()
  add_test(VoxelEditor_Selection_Tests_NOT_BUILT VoxelEditor_Selection_Tests_NOT_BUILT)
endif()
