if(EXISTS "/Users/michaelhalloran/cube_edit/build_test/core/selection/tests/test_performance_core_selection[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_test/core/selection/tests/test_performance_core_selection[1]_tests.cmake")
else()
  add_test(test_performance_core_selection_NOT_BUILT test_performance_core_selection_NOT_BUILT)
endif()
