if(EXISTS "/Users/michaelhalloran/cube_edit/build_debug/tests/integration/rendering/test_integration_visual_pixel_validation_helpers[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_debug/tests/integration/rendering/test_integration_visual_pixel_validation_helpers[1]_tests.cmake")
else()
  add_test(test_integration_visual_pixel_validation_helpers_NOT_BUILT test_integration_visual_pixel_validation_helpers_NOT_BUILT)
endif()
