if(EXISTS "/Users/michaelhalloran/cube_edit/build_test/foundation/memory/tests/test_unit_foundation_memory_pool[1]_tests.cmake")
  include("/Users/michaelhalloran/cube_edit/build_test/foundation/memory/tests/test_unit_foundation_memory_pool[1]_tests.cmake")
else()
  add_test(test_unit_foundation_memory_pool_NOT_BUILT test_unit_foundation_memory_pool_NOT_BUILT)
endif()
